import PDFDocument from "pdfkit";
import type { GeneratedPaper } from "./llm.service";

export async function generatePdfBuffer(
    title: string,
    subject: string,
    totalMarks: number,
    paper: GeneratedPaper
): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, bufferPages: true });
            const buffers: Buffer[] = [];

            doc.on("data", (chunk) => buffers.push(chunk));
            doc.on("end", () => resolve(Buffer.concat(buffers)));
            doc.on("error", (err) => reject(err));

            doc.fillColor("#181818");
            doc.fontSize(22).font("Helvetica-Bold").text(title.toUpperCase(), { align: "center" });
            doc.moveDown(0.2);
            doc.fontSize(14).font("Helvetica").text(`Subject: ${subject}`, { align: "center" });
            doc.moveDown(0.5);

            const startY = doc.y;
            doc.fontSize(10).font("Helvetica-Bold")
                .text(`Total Marks: ${totalMarks}`, 50, startY, { align: "left" });
            doc.text(`Generated by VedaAI`, 50, startY, { align: "right" });
            doc.moveDown(0.8);

            const lineY = doc.y;
            doc.moveTo(50, lineY)
                .lineTo(562, lineY)
                .strokeColor("#cccccc")
                .lineWidth(1)
                .stroke();
            doc.moveDown(1.5);

            for (const section of paper.sections) {
                if (doc.y > 680) doc.addPage();
                doc.fillColor("#272727");
                doc.fontSize(13).font("Helvetica-Bold").text(section.title);

                if (section.instruction) {
                    doc.fontSize(9.5).font("Helvetica-Oblique").fillColor("#555555").text(section.instruction, { lineGap: 3 });
                }
                doc.moveDown(0.8);

                for (const question of section.questions) {
                    if (doc.y > 700) doc.addPage();

                    doc.fillColor("#181818");

                    doc.fontSize(10.5).font("Helvetica-Bold").text(`Q${question.number}. `, { continued: true });
                    doc.font("Helvetica").text(question.text, { continued: true });
                    doc.font("Helvetica-Bold").text(`   [${question.marks} Marks]`, { align: "right" });
                    doc.moveDown(0.3);

                    if (question.options && question.options.length > 0) {
                        for (const option of question.options) {
                            if (doc.y > 730) doc.addPage();
                            doc.fontSize(9.5).font("Helvetica").fillColor("#333333").text(`      ${option}`, { lineGap: 2 });
                        }
                        doc.moveDown(0.4);
                    }
                    doc.moveDown(0.5);
                }
                doc.moveDown(1);
            }

            const pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                doc.fontSize(8).fillColor("#777777")
                    .text(`Page ${i + 1} of ${pages.count}`, 50, 750, { align: "center" });
            }

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
}
